export const CONTROL_PANEL_WIDTH = 320

export const ATTRACTION_INVERSE_SQUARED = 'ATTRACTION_INVERSE_SQUARED'
export const ATTRACTION_INVERSE_LINEAR = 'ATTRACTION_INVERSE_LINEAR'
export const ATTRACTION_CONSTANT = 'ATTRACTION_CONSTANT'
export const ATTRACTION_LINEAR = 'ATTRACTION_LINEAR'
export const ATTRACTION_SQUARED = 'ATTRACTION_SQUARED'
export const ATTRACTION_NONE = 'ATTRACTION_NONE'
